<a href="https://colab.research.google.com/github/KeshavChaurasia/machine-learning-mastery/blob/master/MLM_1_Linear_Algebra_Foundation_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to Numpy

In [ ]:
# Basic numpy instructions 
# np.ndarray() , dtype, shape
import numpy as np

a = np.array([1.0, 2.0, 3.0])

print(a)
print(a.shape)
print(a.dtype)

[1. 2. 3.]
(3,)
float64


In [ ]:
  # function to create numpy array
  # np.empty(), np.zeros(), np.ones()
  import numpy as np

  a = np.empty([3,3])
  print(a)

  b = np.zeros([3,3])
  print(b)

  c = np.ones([2,2])
  print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [ ]:
# Combining Arrays
# Vertical stacking, Horizontal Stacking
import numpy as np

a1 = np.array([1,2,3])
print(a1)

a2 = np.array([4,5,6])
print(a2)

#create vertical stack
a3 = np.vstack((a1,a2))
print(a3)
print(a3.shape)

#create horizontal stack
a4 = np.hstack((a1,a2))
print(a4)
print(a4.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3 4 5 6]
(6,)


Index, Slice and Reshape Numpy arrays

In [ ]:
# 1-D list to Array
import numpy as np

# list
data = [1,2,3,4,5]
print(data)
print(type(data))

# ndarray
data = np.array(data)
print(data)
print(type(data))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 2-D List to Array
import numpy as np

#list
data = [[11,11],
        [22,22],
        [33,33]]
print(data)
print(type(data))

#ndarray
data = np.array(data)
print(data)
print(type(data))

[[11, 11], [22, 22], [33, 33]]
<class 'list'>
[[11 11]
 [22 22]
 [33 33]]
<class 'numpy.ndarray'>


In [ ]:
# indexing
import numpy as np

data = np.array([1,2,3,4])
print(data[0])

data = np.array([[1,2],[2,3]])
print(data[0])
print(data[0][0])
print(data[0,0])

1
[1 2]
1
1


In [ ]:
# Array slicing
# data[from:to]
# 1-D slicing

import numpy as np

data = np.array([11,22,33,44,55])
print(data[:])  # [11 22 33 44 55]
print(data[:1]) # [11]
print(data[-2:]) # [44 55]

[11 22 33 44 55]
[11]
[44 55]


In [ ]:
# 2-D slicing
import numpy as np

data = np.array([
                 [11,22,33],
                 [44,55,66],
                 [77,88,99]
])
X, y = data[:,:-1], data[:,-1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [ ]:
# Split Train and test Rows

import numpy as np

data = np.array([
                 [11,22,33],
                 [44,55,66],
                 [77,88,99]
])

split = 2

train,test = data[:split, :], data[split:, :]
print(train)
print(test)

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


In [ ]:
# Array Reshaping
import numpy as np

data = np.array([11,22,33,44,55])
print(data.shape)

# reshaping 1-D to 2-D array
data = data.reshape((data.shape[0],1))
print(data)
print(data.shape)

# reshaping 2-D to 3-D array
data = np.array([
                 [11,22,33],
                 [44,55,66],
                 [77,88,99]
])
print(data.shape)
data = data.reshape((data.shape[0],data.shape[1],1))
print(data)
print(data.shape)


(5,)
[[11]
 [22]
 [33]
 [44]
 [55]]
(5, 1)
(3, 3)
[[[11]
  [22]
  [33]]

 [[44]
  [55]
  [66]]

 [[77]
  [88]
  [99]]]
(3, 3, 1)


In [2]:
# Broadcasting in Numpy
# broadcast scalar to one-dimensional array

import numpy as np

a = np.array([1,2,3,4])
b = 2
c = a + b

print(c)

# broadcasting scalar to two-dimensional array

a = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
])
b = 2
c = a + b

print(c)

[3 4 5 6]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [3]:
# broadcasting one dimensionaly to two-dimensional array

import numpy as np

a = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
])
b = np.array([1,2,3])
c = a + b
print(c)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
